require('dotenv').config();
const express = require('express');
const cors = require('cors');
const authRoutes = require('./src/routes/authRoutes');
const proveedorRoutes = require('./src/routes/proveedorRoutes');
const sitfiscalRoutes = require('./src/routes/sitfiscalRoutes');
const personalRoutes = require('./src/routes/personalRoutes');
const articuloRoutes = require('./src/routes/articuloRoutes');
const familiaHerramientaRoutes = require('./src/routes/familiaHerramientaRoutes');
const familiaArticuloRoutes = require('./src/routes/familiaArticuloRoutes');
const marcaRoutes = require('./src/routes/marcaRoutes');
const familiaUnidadRoutes = require('./src/routes/familiaUnidadRoutes');
const movimientoRoutes = require('./src/routes/movimientoRoutes');
const lugarRoutes = require('./src/routes/lugarRoutes');
const herramientaRoutes = require('./src/routes/herramientaRoutes');
const herramientaMovimientoRoutes = require('./src/routes/herramientaMovimientoRoutes');
const eppRoutes = require('./src/routes/eppRoutes');
const familiaeppRoutes = require('./src/routes/familiaeppRoutes');
const billetesRoutes = require('./src/routes/billetesRoutes');
const monedaRoutes = require('./src/routes/monedaRoutes');
const motivosRoutes = require('./src/routes/motivosRoutes');
const otrosimpuestosRoutes = require('./src/routes/otrosimpuestosRoutes');
const razonsocialRoutes = require('./src/routes/razonsocialRoutes');
const seccionesRoutes = require('./src/routes/seccionesRoutes');
const tiposRoutes = require('./src/routes/tiposRoutes');
const tipocomprobanteRoutes = require('./src/routes/tipocomprobanteRoutes');
const valoresRoutes = require('./src/routes/valoresRoutes');
const viaticosRoutes = require('./src/routes/viaticosRoutes');
const familiaconceptoRoutes = require('./src/routes/familiaconceptoRoutes');
const plandecompraRoutes = require('./src/routes/plandecompraRoutes');
const empresaRoutes = require('./src/routes/empresaRoutes');
const movilesRoutes = require('./src/routes/movilesRoutes');
const montomovilesRoutes = require('./src/routes/montomovilesRoutes');
const coloresRoutes = require('./src/routes/coloresRoutes');
const tallaRoutes = require('./src/routes/tallaRoutes');
const costosRoutes = require('./src/routes/costosRoutes');
const feriadosRoutes = require('./src/routes/feriadosRoutes');
const preciosRoutes = require('./src/routes/preciosRoutes');
const vehiculosRoutes = require('./src/routes/vehiculosRoutes');
const itemschecklistRoutes = require('./src/routes/itemschecklistRoutes');
const conceptoRoutes = require('./src/routes/conceptoRoutes');
const clientesRoutes = require('./src/routes/clientesRoutes');
const contactoclienteRoutes = require('./src/routes/contactoclienteRoutes');
const serviciosRoutes = require('./src/routes/serviciosRoutes');
const checklistRoutes = require('./src/routes/checklistRoutes');
const movimientostockeRoutes = require('./src/routes/movimientostockeRoutes');
const historialvehicularRoutes = require('./src/routes/historialvehicularRoutes');
const registrovehicularRoutes = require('./src/routes/registrovehicularRoutes');
const facturaventaRoutes = require('./src/routes/facturaventaRoutes');
const reciboRoutes = require('./src/routes/reciboRoutes');
const notacreditoventaRoutes = require('./src/routes/notacreditoventaRoutes');
const remitoventaRoutes = require('./src/routes/remitoventaRoutes');
const devolucionventaRoutes = require('./src/routes/devolucionventaRoutes');
const cotizacionRoutes = require('./src/routes/cotizacionRoutes');
const facturacompraRoutes = require('./src/routes/facturacompraRoutes');
const ordencompraRoutes = require('./src/routes/ordencompraRoutes');
const remitocompraRoutes = require('./src/routes/remitocompraRoutes');
const devolucioncompraRoutes = require('./src/routes/devolucioncompraRoutes');
const notacreditocompraRoutes = require('./src/routes/notacreditocompraRoutes');
const presupuestoRoutes = require('./src/routes/presupuestoRoutes');
const pagosRoutes = require('./src/routes/pagosRoutes');
const otropagosRoutes = require('./src/routes/otropagosRoutes');
const movimientocajaRoutes = require('./src/routes/movimientocajaRoutes');
const reporteRoutes = require('./src/routes/reporteRoutes');
const estadocuenta_clienteRoutes = require('./src/routes/estadocuenta_clienteRoutes');
const reporteivaRoutes = require('./src/routes/reporteivaRoutes');
const reporteivaventasRoutes = require('./src/routes/reporteivaventasRoutes');
const rolesRoutes = require('./src/routes/rolesRoutes');

const app = express();

app.use(cors());
app.use(express.json({ limit: '50mb' }));

app.use('/', authRoutes); // URL final: POST /login
app.use('/proveedor', proveedorRoutes);
app.use('/sitfiscal', sitfiscalRoutes);
app.use('/personal', personalRoutes);
app.use('/articulos', articuloRoutes);
app.use('/familiaherramienta', familiaHerramientaRoutes);
app.use('/familia', familiaHerramientaRoutes);
app.use('/familiarticulos', familiaArticuloRoutes);
app.use('/familiaepp', familiaeppRoutes);
app.use('/marca', marcaRoutes);
app.use('/marcas', marcaRoutes);
app.use('/familiaunidad', familiaUnidadRoutes);
app.use('/movimientostock', movimientoRoutes);
app.use('/lugares', lugarRoutes);
app.use('/herramienta', herramientaRoutes);
app.use('/herramientas', herramientaRoutes);
app.use('/movimientosherramientas', herramientaMovimientoRoutes);
app.use('/movimientos_herramientas', herramientaMovimientoRoutes);
app.use('/movimientostockh', herramientaMovimientoRoutes);
app.use('/epp', eppRoutes);
app.use('/billetes', billetesRoutes);
app.use('/moneda', monedaRoutes);
app.use('/epp-variantes', require('./src/routes/eppVarianteRoutes'));
app.use('/motivos', motivosRoutes);
app.use('/otrosimpuestos', otrosimpuestosRoutes);
app.use('/razonsocial', razonsocialRoutes);
app.use('/secciones', seccionesRoutes);
app.use('/tipos', tiposRoutes);
app.use('/tipocomprobante', tipocomprobanteRoutes);
app.use('/valores', valoresRoutes);
app.use('/viaticos', viaticosRoutes);
app.use('/familiaconcepto', familiaconceptoRoutes);
app.use('/plandecompra', plandecompraRoutes);
app.use('/empresa', empresaRoutes);
app.use('/moviles', movilesRoutes);
app.use('/montomoviles', montomovilesRoutes);
app.use('/colores', coloresRoutes);
app.use('/talla', tallaRoutes);
app.use('/costos', costosRoutes);
app.use('/feriados', feriadosRoutes);
app.use('/precios', preciosRoutes);
app.use('/vehiculos', vehiculosRoutes);
app.use('/itemschecklist', itemschecklistRoutes);
app.use('/concepto', conceptoRoutes);
app.use('/clientes', clientesRoutes);
app.use('/contactocliente', contactoclienteRoutes);
app.use('/servicios', serviciosRoutes);
app.use('/checklist', checklistRoutes);
app.use('/movimientostocke', movimientostockeRoutes);
app.use('/historialvehicular', historialvehicularRoutes);
app.use('/registrovehicular', registrovehicularRoutes);
app.use('/facturaventa', facturaventaRoutes);
app.use('/recibo', reciboRoutes);
app.use('/notacreditoventa', notacreditoventaRoutes);
app.use('/remitoventa', remitoventaRoutes);
app.use('/devolucionventa', devolucionventaRoutes);
app.use('/cotizacion', cotizacionRoutes);
app.use('/facturacompra', facturacompraRoutes);
app.use('/ordencompra', ordencompraRoutes);
app.use('/remitocompra', remitocompraRoutes);
app.use('/devolucioncompra', devolucioncompraRoutes);
app.use('/notacreditocompra', notacreditocompraRoutes);
app.use('/presupuesto', presupuestoRoutes);
app.use('/pagos', pagosRoutes);
app.use('/otropagos', otropagosRoutes);
app.use('/movimientocaja', movimientocajaRoutes);
app.use('/estadocuenta_cliente', estadocuenta_clienteRoutes);
app.use('/estadocuentacliente', estadocuenta_clienteRoutes);
app.use('/reporte', reporteRoutes);
app.use('/reporteiva', reporteivaRoutes);
app.use('/reporteivaventas', reporteivaventasRoutes);
app.use('/roles', rolesRoutes);

const PORT = process.env.PORT || 3400;
app.listen(PORT, '0.0.0.0', () => {
  console.log(`Servidor corriendo en http://0.0.0.0:${PORT}`);
  console.log(`Endpoint: POST /login`);
});